# permissions for end users to edit odoodeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: odoo-operator
    app.kubernetes.io/managed-by: kustomize
  name: odoodeployment-editor-role
rules:
- apiGroups:
  - odoo.abugharbia.com
  resources:
  - odoodeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - odoo.abugharbia.com
  resources:
  - odoodeployments/status
  verbs:
  - get
