# permissions for end users to view odoodployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: odoo-operator
    app.kubernetes.io/managed-by: kustomize
  name: odoodployment-viewer-role
rules:
- apiGroups:
  - odoo.abugharbia.com
  resources:
  - odoodployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - odoo.abugharbia.com
  resources:
  - odoodployments/status
  verbs:
  - get
