---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: 'choice'
        options:
          - 'major'
          - 'minor'
          - 'patch'



jobs:
  create-version:
    name: Create semantic version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the next version
        run: |
          echo "Getting current version"
          current_version=$(git describe --tags --abbrev=0)
          if [[ $? -ne 0 ]]; then
            echo "No tags found, setting version to 0.0.0"
            current_version="0.0.0"
          fi

          echo "Current version: $current_version"

          echo "Getting next version"
          if [[ ${{ github.event.inputs.version }} == 'major' ]]; then
            next_version=$(semver bump major $current_version)
          elif [[ ${{ github.event.inputs.version }} == 'minor' ]]; then
            next_version=$(semver bump minor $current_version)
          elif [[ ${{ github.event.inputs.version }} == 'patch' ]]; then
            next_version=$(semver bump patch $current_version)
          else
            echo "Invalid version"
            exit 1
          fi

          echo "Next version: $next_version"
          echo "::set-output name=next_version::$next_version"

  build-push:
    name: Build and push
    runs-on: ubuntu-latest
    needs: create-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          echo "Building and pushing"
          make docker-buildx VERSION=${{ needs.create-version.outputs.next_version }}

      - name: Make install.yaml
        run: |
          echo "Creating install.yaml"
          make build-installer VERSION=${{ needs.create-version.outputs.next_version }}

      - name: Archive install.yaml
        uses: actions/upload-artifact@v4
        with:
          name: install.yaml
          path: ./dist/install.yaml
          retention-days: 1

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - create-version
      - build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get install.yaml
        uses: actions/download-artifact@v4
        with:
          name: install.yaml
          path: ./dist

      - name: create tag and push
        run: |
          echo "Creating tag and pushing"
          git tag -a ${{ needs.create-version.outputs.next_version }} -m "Release ${{ needs.create-version.outputs.next_version }}"
          git push origin ${{ needs.create-version.outputs.next_version }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.create-version.outputs.next_version }}
          generateReleaseNotes: true
          artifacts: dist/*
          draft: true
